# Generated by Django 6.0.2 on 2026-03-30 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_backfill_admin_email_and_make_required'),
        ('organization', '0003_create_slug_for_old_organizations'),
    ]

    operations = [
    ]
