# Generated by Django 6.0.2 on 2026-04-21 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0002_2_10'),
        ('organization', '0004_merge_20260330_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='djstripe.subscription'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
