# Generated by Django 6.0.2 on 2026-04-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_organization_options_organization_subscription_and_more'),
        ('organization', '0005_organization_slug_non_nullable'),
    ]

    operations = [
    ]
