# Generated by Django 6.0.2 on 2026-04-26 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0005_alter_organization_options_alter_organization_slug"),
        ("organization", "0006_merge_20260421_1353"),
    ]

    operations = []
