# Generated by Django 6.0.2 on 2026-02-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentpermissions',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
